spring:
  application:
    name: ecsite

  datasource:
    url: jdbc:mysql://localhost:3306/ecsite?useSSL=false&serverTimezone=Asia/Tokyo&allowPublicKeyRetrieval=true
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver